---
name: Feature request website
about: Suggest an idea for the website
title: Feature request
labels: feature
assignees: joeryvanegmond

---

name: Feature request
description: File a bug report
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["guardianstournaments/website"]
assignees:
  - joeryvanegmond
body:
  - type: markdown
    attributes:
      value: |
        Please fill the following input fields to define your feature
  - type: input
    id: stakeholder
    attributes:
      label: As a:
      description: Enter the stakeholder (visitor / moderator / user, etc.)
      placeholder: Enter stakeholder
    value: "Visitor"
    validations:
      required: true
  - type: textarea
    id: I-want
    attributes:
      label: I want:
      description: Enter what you want as a stakeholder
      value: "I want the opportunity to create a account by connecting my discord account"
    validations:
      required: true
  - type: textarea
    id: so-I-can
    attributes:
      label: So I can
      description: Why does the stakeholder want this?
    value: "So it is easier to create an account"
    validations:
      required: true
