
name: Deploy on live
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ live ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "SFTP"
  deploy-scripts:
    name: run scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login and run scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: "cd gt_website/live/website/ && .scripts/deploy.sh"
