name: Deploy on testing
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ testing ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "SFTP"
  deploy-scripts:
    name: run scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login and run scripts
        uses: appleboy/ssh-action@master
        with:
          host: ssh.strato.com
          username: guardianstournaments.gg
          port: 22
          password: GT@WEBSIT3
          script: "cd gt_website/testing/website/ && git pull testing testing && cp -r AcademyLeague/public . && cd AcademyLeague && php composer.phar install && php artisan migrate:fresh --seed"
